CREATE TABLE IF NOT EXISTS platform_admins (
 id BIGSERIAL PRIMARY KEY,
 nome VARCHAR(150) NOT NULL,
 usuario VARCHAR(100) NOT NULL UNIQUE,
 senha VARCHAR(255) NOT NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
